# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '14.17.3'
    - run: yarn install
    - run: yarn run codegen
    - run: yarn workspaces run build
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: make secret
      env:
        POSUSUME_FIREBASE_RUN_COMMAND_FILE: ${{ secrets.DEV_POSUSUME_FIREBASE_RUN_COMMAND_FILE }}
    - run: yarn global add firebase-tools
    - run: yarn install
    - run: yarn run codegen
    - run: pwd
    - run: yarn workspaces run build
    - run: |
        firebase use development
        yarn workspaces run test
      name: Run test
      env:
        APP_FIRESTORE_DATABASE_URL: ${{ secrets.DEV_APP_FIRESTORE_DATABASE_URL }}
        APP_STORAGE_BUCKET: ${{ secrets.DEV_APP_STORAGE_BUCKET }}
        GCP_PROJECT_ID: ${{ secrets.DEV_POSUSUME_GCP_PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.DEV_POSUSUME_FIREBASE_TOKEN }}
        APP_GRAPHQL_SCEHMA_PATH: ./packages/graphql/schemas

